name: Generate source packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate:
    name: Generate updated source packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
      - name: Generate
        run: |
          python3 package_sources.py
          touch srcpkg/no-more-failure
      - name: Upload source packages artifact
        uses: actions/upload-artifact@v7
        with:
          name: srcpkgs
          path: srcpkg
      - name: Upload updated metadata artifact
        uses: actions/upload-artifact@v7
        with:
          name: meta-update
          path: |
            lock.json
            manifest.json

